// Generated by scripts/import-osm-network.py. No fabricated national dataset.
import type { OsmNetworkSnapshot } from "./operating-network.js";
export const OSM_NETWORK_DATA: OsmNetworkSnapshot = {
  importedAt: null,
  source: "OpenStreetMap contributors (ODbL 1.0); national import pending",
  stations: [],
  segments: [],
  legacyRoutes: {},
};
