import { RollingStockSpecCatalogEntry } from '../schemas/rolling-stock.schema.js';

export const JAVA_ROLLING_STOCK_CATALOG: ReadonlyArray<RollingStockSpecCatalogEntry> = [
  {
    id: 'SPEC_LOCO_CC206',
    modelName: 'GE CM20EMP (CC206) Heavy Hauler',
    category: 'LOCOMOTIVE',
    buildType: 'MODERN_STEEL',
    bogieType: 'MEDIUM_SPEED_120',
    maximumSpeedKmh: 120,
    passengerCapacity: 0,
    cargoCapacityTons: 0,
    tareWeightTons: 90.0,
    lengthMeters: 20.92,
    energyType: 'DIESEL_ELECTRIC',
    energyConsumptionRate: 3.8, // L/km
    basePurchaseCost: 32_000_000_000, // Rp 32 Miliar
    standardLeadTimeDays: 180,
    standardMaintenanceIntervalKm: 50_000,
    expectedServiceLifeDays: 30 * 365,
    headEndPowerEquipped: false,
    provenance: {
      source: 'PT Kereta Api Indonesia (Persero) Fleet Data & GE Specs',
      sourceDate: '2025-01-15',
      verified: true,
      notes: 'Heavy dual-cab diesel-electric locomotive deployed on Java trunk intercity & container lines.',
    },
  },
  {
    id: 'SPEC_LOCO_CC201',
    modelName: 'GE U18C (CC201) Universal Diesel',
    category: 'LOCOMOTIVE',
    buildType: 'CONVENTIONAL_STEEL',
    bogieType: 'LOW_SPEED_100',
    maximumSpeedKmh: 100,
    passengerCapacity: 0,
    cargoCapacityTons: 0,
    tareWeightTons: 84.0,
    lengthMeters: 14.13,
    energyType: 'DIESEL_ELECTRIC',
    energyConsumptionRate: 3.0, // L/km
    basePurchaseCost: 18_000_000_000, // Rp 18 Miliar
    standardLeadTimeDays: 120,
    standardMaintenanceIntervalKm: 40_000,
    expectedServiceLifeDays: 25 * 365,
    headEndPowerEquipped: false,
    provenance: {
      source: 'PT KAI Locomotive Registry',
      sourceDate: '2025-01-15',
      verified: true,
      notes: 'General purpose secondary line and local passenger locomotive.',
    },
  },
  {
    id: 'SPEC_COACH_K1_EXEC',
    modelName: 'K1 Stainless Steel Eksekutif',
    category: 'PASSENGER_CARRIAGE',
    passengerClass: 'EXECUTIVE',
    buildType: 'STAINLESS_STEEL',
    bogieType: 'MEDIUM_SPEED_120',
    maximumSpeedKmh: 120,
    passengerCapacity: 50,
    cargoCapacityTons: 0,
    tareWeightTons: 38.0,
    lengthMeters: 20.0,
    energyType: 'DIESEL_ELECTRIC',
    energyConsumptionRate: 0,
    basePurchaseCost: 7_500_000_000, // Rp 7.5 Miliar
    standardLeadTimeDays: 120,
    standardMaintenanceIntervalKm: 50_000,
    expectedServiceLifeDays: 25 * 365,
    headEndPowerEquipped: false,
    provenance: {
      source: 'PT INKA Production Catalog',
      sourceDate: '2025-01-15',
      verified: true,
      notes: 'Modern air-conditioned executive coach produced by PT INKA Madiun.',
    },
  },
  {
    id: 'SPEC_COACH_K3_PREMIUM',
    modelName: 'K3 Premium Modern Ekonomi',
    category: 'PASSENGER_CARRIAGE',
    passengerClass: 'ECONOMY',
    buildType: 'STAINLESS_STEEL',
    bogieType: 'LOW_SPEED_100',
    maximumSpeedKmh: 100,
    passengerCapacity: 80,
    cargoCapacityTons: 0,
    tareWeightTons: 36.0,
    lengthMeters: 20.0,
    energyType: 'DIESEL_ELECTRIC',
    energyConsumptionRate: 0,
    basePurchaseCost: 5_500_000_000, // Rp 5.5 Miliar
    standardLeadTimeDays: 90,
    standardMaintenanceIntervalKm: 45_000,
    expectedServiceLifeDays: 20 * 365,
    headEndPowerEquipped: false,
    provenance: {
      source: 'PT INKA Production Catalog',
      sourceDate: '2025-01-15',
      verified: true,
      notes: 'High-density reclining economy carriage for regional and intercity trains.',
    },
  },
  {
    id: 'SPEC_COACH_K1_LUXURY',
    modelName: 'K1 Luxury Sleeper / Suite Class',
    category: 'PASSENGER_CARRIAGE',
    passengerClass: 'LUXURY',
    buildType: 'STAINLESS_STEEL',
    bogieType: 'MEDIUM_SPEED_120',
    maximumSpeedKmh: 120,
    passengerCapacity: 18,
    cargoCapacityTons: 0,
    tareWeightTons: 40.0,
    lengthMeters: 20.0,
    energyType: 'DIESEL_ELECTRIC',
    energyConsumptionRate: 0,
    basePurchaseCost: 12_000_000_000, // Rp 12 Miliar
    standardLeadTimeDays: 150,
    standardMaintenanceIntervalKm: 50_000,
    expectedServiceLifeDays: 25 * 365,
    headEndPowerEquipped: false,
    provenance: {
      source: 'PT INKA Luxury Car Series Specs',
      sourceDate: '2025-01-15',
      verified: true,
      notes: 'Flagship sleeper compartment carriage with individual lie-flat seats.',
    },
  },
  {
    id: 'SPEC_COACH_M1_DINING',
    modelName: 'M1 Kereta Makan (Restorasi)',
    category: 'DINING_CAR',
    buildType: 'STAINLESS_STEEL',
    bogieType: 'MEDIUM_SPEED_120',
    maximumSpeedKmh: 120,
    passengerCapacity: 24, // dining seats
    cargoCapacityTons: 5.0, // kitchen provisions
    tareWeightTons: 42.0,
    lengthMeters: 20.0,
    energyType: 'DIESEL_ELECTRIC',
    energyConsumptionRate: 0,
    basePurchaseCost: 6_000_000_000, // Rp 6 Miliar
    standardLeadTimeDays: 90,
    standardMaintenanceIntervalKm: 45_000,
    expectedServiceLifeDays: 25 * 365,
    headEndPowerEquipped: false,
    provenance: {
      source: 'PT KAI Dining Services Standard Spec',
      sourceDate: '2025-01-15',
      verified: true,
      notes: 'Full commercial kitchen and dining area for intercity trains.',
    },
  },
  {
    id: 'SPEC_VAN_P_GENERATOR',
    modelName: 'P Kereta Pembangkit (Power Van)',
    category: 'POWER_GENERATOR_CAR',
    buildType: 'STAINLESS_STEEL',
    bogieType: 'MEDIUM_SPEED_120',
    maximumSpeedKmh: 120,
    passengerCapacity: 0,
    cargoCapacityTons: 3.0,
    tareWeightTons: 45.0,
    lengthMeters: 20.0,
    energyType: 'DIESEL_ELECTRIC',
    energyConsumptionRate: 0.8, // auxiliary fuel L/km
    basePurchaseCost: 5_000_000_000, // Rp 5 Miliar
    standardLeadTimeDays: 90,
    standardMaintenanceIntervalKm: 40_000,
    expectedServiceLifeDays: 20 * 365,
    headEndPowerEquipped: false,
    provenance: {
      source: 'PT INKA Generator Car Specifications',
      sourceDate: '2025-01-15',
      verified: true,
      notes: 'Diesel-powered auxiliary generator van supplying hotel power (AC, lighting) to consist.',
    },
  },
  {
    id: 'SPEC_WAGON_PPCW_CONTAINER',
    modelName: 'Gerbong Datar Kontainer PPCW 40ft',
    category: 'CONTAINER_WAGON',
    buildType: 'CONVENTIONAL_STEEL',
    bogieType: 'LOW_SPEED_100',
    maximumSpeedKmh: 100,
    passengerCapacity: 0,
    cargoCapacityTons: 54.0,
    tareWeightTons: 16.0,
    lengthMeters: 14.5,
    energyType: 'DIESEL_ELECTRIC',
    energyConsumptionRate: 0,
    basePurchaseCost: 950_000_000, // Rp 950 Juta
    standardLeadTimeDays: 45,
    standardMaintenanceIntervalKm: 60_000,
    expectedServiceLifeDays: 30 * 365,
    headEndPowerEquipped: false,
    provenance: {
      source: 'PT KAI Freight Services Technical Data',
      sourceDate: '2025-01-15',
      verified: true,
      notes: 'Flatcar with twist locks for ISO 20ft/40ft shipping container freight.',
    },
  },
  {
    id: 'SPEC_WAGON_ZZOW_COAL',
    modelName: 'Gerbong Terbuka ZZOW Batubara',
    category: 'COMMODITY_WAGON',
    buildType: 'CONVENTIONAL_STEEL',
    bogieType: 'LOW_SPEED_100',
    maximumSpeedKmh: 90,
    passengerCapacity: 0,
    cargoCapacityTons: 50.0,
    tareWeightTons: 18.0,
    lengthMeters: 13.8,
    energyType: 'DIESEL_ELECTRIC',
    energyConsumptionRate: 0,
    basePurchaseCost: 1_200_000_000, // Rp 1.2 Miliar
    standardLeadTimeDays: 60,
    standardMaintenanceIntervalKm: 50_000,
    expectedServiceLifeDays: 30 * 365,
    headEndPowerEquipped: false,
    provenance: {
      source: 'PT KAI Bulk Commodity Spec',
      sourceDate: '2025-01-15',
      verified: true,
      notes: 'High-side open hopper wagon for bulk industrial freight.',
    },
  },
];
