import { StationCatalogEntry } from '../schemas/station.schema.js';

export const JAVA_STATION_CATALOG: ReadonlyArray<StationCatalogEntry> = Object.freeze([
  {
    id: 'STN_GMR_GAMBIR',
    code: 'GMR',
    name: 'Stasiun Gambir',
    region: 'DAOP_1_JAKARTA',
    coordinates: {
      lat: -6.1767,
      lng: 106.8306,
    },
    platformCount: 4,
    maxTrainLengthMeters: 400,
    facilities: {
      hasCargoTerminal: false,
      hasDepotConnection: false,
      hasExecutiveLounge: true,
    },
    demandProfile: {
      baseDailyDemand: 28000,
      commuterShare: 0.15,
      businessShare: 0.55,
      touristShare: 0.3,
    },
    provenance: {
      source: 'PT Kereta Api Indonesia (Persero) - Buku Informasi Stasiun DAOP 1',
      sourceDate: '2026-01-15',
      verified: true,
      notes: 'Premier executive terminal station in Central Jakarta. Elevated 4-track island configuration.',
    },
  },
  {
    id: 'STN_BD_BANDUNG',
    code: 'BD',
    name: 'Stasiun Bandung',
    region: 'DAOP_2_BANDUNG',
    coordinates: {
      lat: -6.9142,
      lng: 107.6025,
    },
    platformCount: 6,
    maxTrainLengthMeters: 350,
    facilities: {
      hasCargoTerminal: false,
      hasDepotConnection: true,
      hasExecutiveLounge: true,
    },
    demandProfile: {
      baseDailyDemand: 22000,
      commuterShare: 0.2,
      businessShare: 0.35,
      touristShare: 0.45,
    },
    provenance: {
      source: 'PT Kereta Api Indonesia (Persero) - Buku Informasi Stasiun DAOP 2',
      sourceDate: '2026-01-15',
      verified: true,
      notes: 'Main terminal in Bandung. Directly co-located with Depo Kereta & Lokomotif Bandung.',
    },
  },
  {
    id: 'STN_CN_CIREBON',
    code: 'CN',
    name: 'Stasiun Cirebon',
    region: 'DAOP_3_CIREBON',
    coordinates: {
      lat: -6.7053,
      lng: 108.5554,
    },
    platformCount: 6,
    maxTrainLengthMeters: 350,
    facilities: {
      hasCargoTerminal: true,
      hasDepotConnection: true,
      hasExecutiveLounge: true,
    },
    demandProfile: {
      baseDailyDemand: 14000,
      commuterShare: 0.25,
      businessShare: 0.45,
      touristShare: 0.3,
    },
    provenance: {
      source: 'PT Kereta Api Indonesia (Persero) - DAOP 3 Kejaksan Profil Stasiun',
      sourceDate: '2026-01-15',
      verified: true,
      notes: 'Strategic junction connecting Northern trunk line with Southern trans-Java line via Purwokerto.',
    },
  },
  {
    id: 'STN_SMT_SEMARANGTAWANG',
    code: 'SMT',
    name: 'Stasiun Semarang Tawang',
    region: 'DAOP_4_SEMARANG',
    coordinates: {
      lat: -6.9644,
      lng: 110.4278,
    },
    platformCount: 8,
    maxTrainLengthMeters: 380,
    facilities: {
      hasCargoTerminal: true,
      hasDepotConnection: true,
      hasExecutiveLounge: true,
    },
    demandProfile: {
      baseDailyDemand: 18000,
      commuterShare: 0.25,
      businessShare: 0.45,
      touristShare: 0.3,
    },
    provenance: {
      source: 'PT Kereta Api Indonesia (Persero) - Profil Stasiun DAOP 4 Semarang',
      sourceDate: '2026-01-15',
      verified: true,
      notes: 'Historic Pantura hub station. Connected to Tanjung Emas port container logistics branch.',
    },
  },
  {
    id: 'STN_YK_YOGYAKARTA',
    code: 'YK',
    name: 'Stasiun Yogyakarta',
    region: 'DAOP_6_YOGYAKARTA',
    coordinates: {
      lat: -7.7892,
      lng: 110.3635,
    },
    platformCount: 6,
    maxTrainLengthMeters: 350,
    facilities: {
      hasCargoTerminal: false,
      hasDepotConnection: true,
      hasExecutiveLounge: true,
    },
    demandProfile: {
      baseDailyDemand: 24000,
      commuterShare: 0.2,
      businessShare: 0.25,
      touristShare: 0.55,
    },
    provenance: {
      source: 'PT Kereta Api Indonesia (Persero) - DAOP 6 Yogyakarta Data Operasi',
      sourceDate: '2026-01-15',
      verified: true,
      notes: 'Primary tourism and cultural gateway in Central Java. Electrified terminal for KRL Commuter Line.',
    },
  },
  {
    id: 'STN_SLO_SOLOBALAPAN',
    code: 'SLO',
    name: 'Stasiun Solo Balapan',
    region: 'DAOP_6_YOGYAKARTA',
    coordinates: {
      lat: -7.5568,
      lng: 110.8214,
    },
    platformCount: 8,
    maxTrainLengthMeters: 350,
    facilities: {
      hasCargoTerminal: true,
      hasDepotConnection: true,
      hasExecutiveLounge: true,
    },
    demandProfile: {
      baseDailyDemand: 16000,
      commuterShare: 0.35,
      businessShare: 0.3,
      touristShare: 0.35,
    },
    provenance: {
      source: 'PT Kereta Api Indonesia (Persero) - DAOP 6 Profil Stasiun Solo Balapan',
      sourceDate: '2026-01-15',
      verified: true,
      notes: 'Key junction connecting Yogyakarta, Semarang (via Gundih), and East Java (via Madiun).',
    },
  },
  {
    id: 'STN_SGU_SURABAYAGUBENG',
    code: 'SGU',
    name: 'Stasiun Surabaya Gubeng',
    region: 'DAOP_8_SURABAYA',
    coordinates: {
      lat: -7.2653,
      lng: 112.7522,
    },
    platformCount: 7,
    maxTrainLengthMeters: 400,
    facilities: {
      hasCargoTerminal: false,
      hasDepotConnection: true,
      hasExecutiveLounge: true,
    },
    demandProfile: {
      baseDailyDemand: 26000,
      commuterShare: 0.25,
      businessShare: 0.5,
      touristShare: 0.25,
    },
    provenance: {
      source: 'PT Kereta Api Indonesia (Persero) - DAOP 8 Surabaya Data Stasiun',
      sourceDate: '2026-01-15',
      verified: true,
      notes: 'Largest passenger terminal station in East Java. Connects Southern and Northern corridors.',
    },
  },
]);
