import { TrackCorridorSegment } from '../schemas/track.schema.js';

export const JAVA_TRACK_CORRIDOR_SEGMENTS: ReadonlyArray<TrackCorridorSegment> = Object.freeze([
  {
    id: 'SEG_GMR_BD',
    name: 'Koridor Gambir - Bandung',
    originStationId: 'STN_GMR_GAMBIR',
    destinationStationId: 'STN_BD_BANDUNG',
    distanceKm: 160.0,
    maxSpeedKmh: 100,
    trackSpeedLimitKmh: 100,
    isElectrified: false,
    isDoubleTrack: false,
    trackGaugeMm: 1067,
    provenance: {
      source: 'PT Kereta Api Indonesia (Persero) - Gapeka Lintas Jawa / ECONOMY_RULES.md §5.3',
      sourceDate: '2026-01-15',
      verified: true,
      notes: 'Authoritative reference test vector distance (160 km). Padalarang mountainous restrictions apply.',
    },
  },
  {
    id: 'SEG_GMR_CN',
    name: 'Koridor Gambir - Cirebon',
    originStationId: 'STN_GMR_GAMBIR',
    destinationStationId: 'STN_CN_CIREBON',
    distanceKm: 219.0,
    maxSpeedKmh: 120,
    trackSpeedLimitKmh: 120,
    isElectrified: false,
    isDoubleTrack: true,
    trackGaugeMm: 1067,
    provenance: {
      source: 'PT Kereta Api Indonesia (Persero) - Gapeka Lintas Pantura Barat',
      sourceDate: '2026-01-15',
      verified: true,
      notes: 'Lintas Pantura ganda Cikampek - Cirebon. High speed alignment.',
    },
  },
  {
    id: 'SEG_CN_SMT',
    name: 'Koridor Cirebon - Semarang Tawang',
    originStationId: 'STN_CN_CIREBON',
    destinationStationId: 'STN_SMT_SEMARANGTAWANG',
    distanceKm: 225.7,
    maxSpeedKmh: 120,
    trackSpeedLimitKmh: 120,
    isElectrified: false,
    isDoubleTrack: true,
    trackGaugeMm: 1067,
    provenance: {
      source: 'PT Kereta Api Indonesia (Persero) - Buku Jarak Operasi DAOP 3 & 4',
      sourceDate: '2026-01-15',
      verified: true,
      notes: 'Pantura Central double-track line via Tegal and Pekalongan.',
    },
  },
  {
    id: 'SEG_SMT_SGU',
    name: 'Koridor Semarang Tawang - Surabaya Gubeng',
    originStationId: 'STN_SMT_SEMARANGTAWANG',
    destinationStationId: 'STN_SGU_SURABAYAGUBENG',
    distanceKm: 295.0,
    maxSpeedKmh: 120,
    trackSpeedLimitKmh: 120,
    isElectrified: false,
    isDoubleTrack: true,
    trackGaugeMm: 1067,
    provenance: {
      source: 'PT Kereta Api Indonesia (Persero) - Gapeka Pantura Timur',
      sourceDate: '2026-01-15',
      verified: true,
      notes: 'Pantura East mainline via Cepu and Bojonegoro connecting into Surabaya.',
    },
  },
  {
    id: 'SEG_CN_YK',
    name: 'Koridor Cirebon - Yogyakarta',
    originStationId: 'STN_CN_CIREBON',
    destinationStationId: 'STN_YK_YOGYAKARTA',
    distanceKm: 312.0,
    maxSpeedKmh: 110,
    trackSpeedLimitKmh: 110,
    isElectrified: false,
    isDoubleTrack: true,
    trackGaugeMm: 1067,
    provenance: {
      source: 'PT Kereta Api Indonesia (Persero) - Gapeka Lintas Tengah Kroya',
      sourceDate: '2026-01-15',
      verified: true,
      notes: 'Double track link connecting Cirebon, Purwokerto, Kroya, and Yogyakarta.',
    },
  },
  {
    id: 'SEG_BD_YK',
    name: 'Koridor Bandung - Yogyakarta',
    originStationId: 'STN_BD_BANDUNG',
    destinationStationId: 'STN_YK_YOGYAKARTA',
    distanceKm: 400.0,
    maxSpeedKmh: 90,
    trackSpeedLimitKmh: 90,
    isElectrified: false,
    isDoubleTrack: false,
    trackGaugeMm: 1067,
    provenance: {
      source: 'PT Kereta Api Indonesia (Persero) - Gapeka Lintas Selatan Priangan',
      sourceDate: '2026-01-15',
      verified: true,
      notes: 'Scenic southern route via Tasikmalaya and Banjar. Single track mountainous alignment.',
    },
  },
  {
    id: 'SEG_YK_SLO',
    name: 'Koridor Yogyakarta - Solo Balapan',
    originStationId: 'STN_YK_YOGYAKARTA',
    destinationStationId: 'STN_SLO_SOLOBALAPAN',
    distanceKm: 60.0,
    maxSpeedKmh: 120,
    trackSpeedLimitKmh: 120,
    isElectrified: true,
    isDoubleTrack: true,
    trackGaugeMm: 1067,
    provenance: {
      source: 'Direktorat Jenderal Perkeretaapian - Proyek Elektrifikasi Solo-Yogya',
      sourceDate: '2026-01-15',
      verified: true,
      notes: 'Fully electrified 1500V DC overhead catenary double track corridor.',
    },
  },
  {
    id: 'SEG_SLO_SGU',
    name: 'Koridor Solo Balapan - Surabaya Gubeng',
    originStationId: 'STN_SLO_SOLOBALAPAN',
    destinationStationId: 'STN_SGU_SURABAYAGUBENG',
    distanceKm: 250.0,
    maxSpeedKmh: 120,
    trackSpeedLimitKmh: 120,
    isElectrified: false,
    isDoubleTrack: true,
    trackGaugeMm: 1067,
    provenance: {
      source: 'PT Kereta Api Indonesia (Persero) - Gapeka Jalur Ganda Lintas Selatan Jawa',
      sourceDate: '2026-01-15',
      verified: true,
      notes: 'Completed trans-Java southern double track via Madiun and Kertosono.',
    },
  },
  {
    id: 'SEG_SMT_SLO',
    name: 'Koridor Semarang Tawang - Solo Balapan',
    originStationId: 'STN_SMT_SEMARANGTAWANG',
    destinationStationId: 'STN_SLO_SOLOBALAPAN',
    distanceKm: 107.0,
    maxSpeedKmh: 90,
    trackSpeedLimitKmh: 90,
    isElectrified: false,
    isDoubleTrack: false,
    trackGaugeMm: 1067,
    provenance: {
      source: 'PT Kereta Api Indonesia (Persero) - Profil Jalur Semarang - Gundih - Solo',
      sourceDate: '2026-01-15',
      verified: true,
      notes: 'Historic transversal branch connecting Central Java North and South networks.',
    },
  },
]);
